steps:
- name: 'ubuntu'
  args: ['printenv']
  
# Run FortiDevSec SAST Scanner, once the build step is done.  
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args: ['-c','docker run  --rm --network=cloudbuild-e TRIGGER_NAME=$TRIGGER_NAME -e COMMIT_SHA=$COMMIT_SHA -e BRANCH_NAME=$BRANCH_NAME -e TAG_NAME=$TAG_NAME --mount type=bind,source=$(pwd),target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest env']
# Run FortiDevSec DAST Scanner, once the deploy step is don
- name: 'gcr.io/cloud-builders/docker'
  args: ['-c','printenv']
